#!/usr/bin/env bash

# Create our vpc
VPC_ID=$(aws ec2 create-vpc \
--cidr-block 172.1.0.0/16 \
--region us-east-1 \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]" \
--query "Vpc.VpcId" \
--output text)

echo "VPC ID: $VPC_ID"

# Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--region us-east-1 \
--tag-specifications "ResourceType=internet-gateway,Tags=[{Key=Name,Value=my-igw-3}]" \
--query "InternetGateway.InternetGatewayId" \
--output text)

echo "IGW ID: $IGW_ID"

# Turn on DNS hostname
aws ec2 modify-vpc-attribute \
--vpc-id $VPC_ID \
--enable-dns-hostnames "{\"Value\": true}" \
--region us-east-1

# Attach an IGW
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --region us-east-1

# Create a new subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 172.1.0.0/20 \
--region us-east-1 \
--tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=my-subnet-3}]" \
--query "Subnet.SubnetId" \
--output text)

echo "Subnet ID: $SUBNET_ID"

# Auto assign IPv4 addresses
aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--map-public-ip-on-launch \
--region us-east-1

# Explicitly associate the subnet with the vpc
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--region us-east-1 \
--query "RouteTables[0].RouteTableId" \
--output text)

echo "Route Table ID: $RT_ID"

# Add a route for our RT to our IGW
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID \
--region us-east-1

echo "Route created"

# Print out delete command
echo "./delete_vpc $VPC_ID $IGW_ID $SUBNET_ID"

