#!/usr/bin/env bash

echo "Creating bucket..."

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration "LocationConstraint=us-west-2" \
--query "Location" \
--output text

echo "Bucket created"