#!/usr/bin/env bash
echo "Deleting bucket..."

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME

echo "Bucket deleted"