#!/usr/bin/env bash

echo "Listing objects..."

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects --bucket $BUCKET_NAME > objects_list.json

echo "Objects listed"