#!/usr/bin/env bash

echo "Putting object..."

if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

if [ -z "$2" ]; then
    echo "No filename provided"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename $FILENAME)

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY

echo "Object put"