#!/usr/bin/env bash

echo "==deploy==="

STACK_NAME="aws-asg-ec2-basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME
